apiVersion: deployments.plural.sh/v1alpha1
kind: Cluster
metadata:
  name: existing
  namespace: default
spec:
  handle: lukasz
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: full-access
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: full-access
    namespace: default
---
apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  labels:
    app.kubernetes.io/name: infrastructurestack
    app.kubernetes.io/instance: infrastructurestack-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: mlflow
  namespace: default
spec:
  name: mlflow
  detach: true
  type: TERRAFORM
  approval: true
  manageState: true
  actor: lukasz@plural.sh
  configuration:
    version: "1.8"
  clusterRef:
    name: existing
    namespace: default
  git:
    ref: main
    folder: terraform
    url: https://github.com/zreigz/mlflow.git
  jobSpec:
    namespace: default
    serviceAccount: full-access

---
apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: mlflow
  namespace: default
spec:
  syncConfig:
    createNamespace: true
    deleteNamespace: true
    enforceNamespace: true
  namespace: mlflow
  name: mlflow
  helm:
    version: "1.8.1"
    chart: mlflow
    release: mlflow
    ignoreHooks: false
    url: https://community-charts.github.io/helm-charts
    valuesFiles:
      - mlflow.yaml
  imports:
    - stackRef:
        name: mlflow
        namespace: default
  configuration:
    stackName: mlflow
  git:
    ref: main
    folder: helm
    url: https://github.com/zreigz/mlflow.git
  clusterRef:
    name: existing
    namespace: default

